#!/usr/bin/env python

import sys
import clitool
import mc_bin_client

def cmd(f):
    """Decorate a function with code to authenticate based on 2
    arguments past the normal number of arguments."""

    def g(*args, **kwargs):
        mc = args[0]
        n = f.func_code.co_argcount
        mc.sasl_auth_plain(args[1], args[2])
        f(mc, *args[3:n+1])

    return g

@cmd
def create_bucket(mc, name, engine, config=''):
    mc.bucket_create(name, engine, config)
    print "Bucket '{0}' create with engine '{1}' and config '{2}'".format(name, engine, config)

@cmd
def delete_bucket(mc, name, config='force=false'):
    mc.delete_bucket(mc, name, config)
    print "Bucket '{0}' deleted using config '{1}".format(name, config)

@cmd
def list_buckets(mc):
    print mc.bucket_list()

def main():
    c = clitool.CliTool()
    c.addCommand('create', create_bucket, 'create username password name engine [config]')
    c.addCommand('delete', delete_bucket, 'delete username password name [config]')
    c.addCommand('list-buckets', list_buckets, 'list-buckets username password')
    c.execute()

if __name__ == '__main__':
    main()
