Document: memcached-bucket-engine
Title: Debian memcached-bucket-engine Manual
Author: <insert document author here>
Abstract: This manual describes what memcached-bucket-engine is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/memcached-bucket-engine/memcached-bucket-engine.sgml.gz

Format: postscript
Files: /usr/share/doc/memcached-bucket-engine/memcached-bucket-engine.ps.gz

Format: text
Files: /usr/share/doc/memcached-bucket-engine/memcached-bucket-engine.text.gz

Format: HTML
Index: /usr/share/doc/memcached-bucket-engine/html/index.html
Files: /usr/share/doc/memcached-bucket-engine/html/*.html
